id: DA55D0E35
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:51:31+00:00'
last_modified: '2022-05-27T05:23:14.128840+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9a93:
      image_group_id: I1PD95897
      title: སྡུད་པ་ཚིགས་སུ་བཅད་པའི་དཀའ་འགྲེལ།
      total_pages: 1426
      order: 52
      base_file: 9a93.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
