id: PEE47EEE8
initial_creation_type: ocr
source_metadata:
  volumes:
    32517091fb9a496d8b29b71a8f481104:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: སྡུད་པ་ཚིགས་སུ་བཅད་པའི་དཀའ་འགྲེལ།
      total_pages: 1426
      volume_number: 52
vol2fn:
  v052: v052.txt
